const classroomStudents = [
  "abraham-saavedra",
  "albert-mosella",
  "albert-sagol",
  "alex-gomez",
  "bernat-arcusa",
  "boris-randebrock",
  "cristian-bermudez",
  "daniel-montes",
  "daniell-marafon",
  "elias-heresi",
  "emanuele-panesi",
  "facundo-tolosa",
  "francesco-fabrissin",
  "gerard-albajar",
  "ignasi-reixach",
  "josep-andreu",
  "luc-st-pierre",
  "luis-dudamel",
  "maicol-torres",
  "mariadelmar-cegarra",
  "mariam-lliso",
  "marian-lopez",
  "nacho-losada",
  "olga-tsybikova",
  "tomas-sanchez",
  "victor-arumi",
  "victor-braz",
];

module.exports = classroomStudents;
