const classroomStudents = [
  "berto-forteza",
  "adria-martinez",
  "andrea-pedreño",
  "arnau-oriol",
  "benjamin-rae",
  "carlos-delblanco",
  "catalina-tarelli",
  "cristina-fores",
  "enric-vazquez",
  "guillem-trave",
  "mireia-rull",
  "nuria-ramoneda",
  "oriol-raventos",
  "rodrigo-rosales",
  "victor-redondo",
  "xavier-sans",
  "albert-valls",
  "andoni-goicoechea",
  "david-cuartas",
  "jordi-font",
  "jose-ramos",
  "victor-merino",
  "zhenzhi-jin",
  "alvaro-parada",
];

module.exports = classroomStudents;
